### PR TITLE
Added diagram showing Envoy Personas

### PR DESCRIPTION
**Pull request by itzg**
# What

I was thinking that we have the whole Salus bundle and docs area, yet an outsider wanting to use Salus can't see the bigger picture (literally) of Salus.

# How

There are couple more diagrams I can probably scrub for public consumption, but the Envoy Personas (agent, poller, etc) seemed like an easy one to include.

### CODE REVIEW

**Comment by itzg** [comment]
> There's no line to connect the envoy as private poller to ambassador?

Oops, I'll add that somehow.

**Comment by GeorgeJahad** [comment]
shouldn't there also by a line to connect the public poller to the ambassador?

**Comment by itzg** [comment]
> shouldn't there also by a line to connect the public poller to the ambassador?

Yes :) Not sure how I left out these two important connections, but I'm glad I got some reviews of it.

**Comment by itzg** [comment]
@GeorgeJahad , I fixed the public poller connection.

**Comment by itzg** [comment]
I had totally forgotten about this PR :)

**Pull request merged**
